name: CI/CD
on: push

jobs:
  build_debug:
    runs-on: ubuntu-latest
    name: build_debug
    steps:
      - name: Download Conan package manager
        run: |
          pip3 install conan
          conan --version
      - name: Clone source
        uses: actions/checkout@v2
      - name: Configure	
        shell: bash
        run: |
          mkdir ${{runner.workspace}}/build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: bash
        run: cmake --build build -j 16
      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest
