name: CI/CD
on: push

jobs:
  build_debug:
    runs-on: ubuntu-latest
    name: build_debug
    steps:
      - name: Clone source
        uses: actions/checkout@v2
      - name: Download Conan package manager
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          sudo ln -s ~/.local/bin/conan /usr/local/bin/conan
          conan --version
      - name: Configure	
        run: |
          mkdir ${{runner.workspace}}/build
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -j 16
      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: ctest
