name: CI/CD
on: push

jobs:
  build_debug:
    runs-on: conanio/gcc7
    name: build_debug
    steps:
      - uses: actions/checkout@v2
      - name: Create build directory
        shell: bash
        run: mkdir ${{runner.workspace}}/build
      - name: Configure	
        shell: bash
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: bash
        run: cmake --build build -j 16
      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ctest
